tasks:
  - curl -sSfL https://dot.net/v1/dotnet-install.sh | sudo bash -s -- -c 6.0 -i /usr/bin/
  - curl -sSfL https://dot.net/v1/dotnet-install.sh | sudo bash -s -- -v 3.1.0 --runtime aspnetcore -i /usr/bin/